import { Lead, Agent, Cadence, WhatsappDispatch, EmailTemplate, Integration, DashboardStats } from './types';

export const initialStats: DashboardStats = {
  totalLeads: 1482,
  whatsappValids: 1390,
  opportunitiesCount: 624,
  responseRate: 34.2,
  dispatchesToday: 480,
  pipelineValue: 285000,
};

export const initialLeads: Lead[] = [
  {
    id: 'lead-1',
    name: 'Carlos Eduardo Santos',
    company: 'Imobiliária Prime SP',
    segment: 'Imobiliária',
    city: 'São Paulo - SP',
    phone: '(11) 98765-4321',
    whatsappValid: true,
    email: 'contato@imobiliariaprimesp.com.br',
    website: '',
    siteStatus: 'SEM_SITE',
    instagram: '@imobiliariaprimesp',
    cnpj: '12.345.678/0001-90',
    opportunityScore: 'HIGH',
    scoreReason: 'Não possui site institucional e tem alto volume de imóveis no Instagram. Excelente oportunidade para venda de portal imobiliário com IA.',
    status: 'NOVO_LEAD',
    origin: 'Google Maps Scraping',
    estimatedValue: 12000,
    lastInteraction: '2026-08-06 10:15',
    lastChannel: 'WHATSAPP',
    createdAt: '2026-08-05',
  },
  {
    id: 'lead-2',
    name: 'Dra. Patricia Lima',
    company: 'Clínica Odonto Glow',
    segment: 'Odontologia / Saúde',
    city: 'Campinas - SP',
    phone: '(19) 99123-8877',
    whatsappValid: true,
    email: 'patricia@odontoglow.com',
    website: 'www.odontoglow.com.br',
    siteStatus: 'DESATUALIZADO',
    instagram: '@odontoglow_campinas',
    cnpj: '23.456.789/0001-01',
    opportunityScore: 'MEDIUM',
    scoreReason: 'Site antigo sem SSL, não responsivo e sem agendamento online automático.',
    status: 'CONTATO_INICIADO',
    origin: 'Google Maps Scraping',
    estimatedValue: 8500,
    lastInteraction: '2026-08-06 09:30',
    lastChannel: 'WHATSAPP',
    createdAt: '2026-08-04',
  },
  {
    id: 'lead-3',
    name: 'Roberto Mendonça',
    company: 'Mendonça & Associados Advocacia',
    segment: 'Advocacia',
    city: 'Rio de Janeiro - RJ',
    phone: '(21) 97654-3210',
    whatsappValid: true,
    email: 'roberto@mendoncaadv.com.br',
    website: '',
    siteStatus: 'SEM_SITE',
    instagram: '',
    cnpj: '34.567.890/0001-12',
    opportunityScore: 'HIGH',
    scoreReason: 'Sem presença digital estruturada nem site. Escritório com CNPJ ativo desde 2018.',
    status: 'RESPONDEU',
    origin: 'Google Scraping + CNPJ',
    estimatedValue: 15000,
    lastInteraction: '2026-08-06 11:45',
    lastChannel: 'WHATSAPP',
    notes: 'Solicitou apresentação de portfólio via WhatsApp. Demonstrará para sócios.',
    createdAt: '2026-08-03',
  },
  {
    id: 'lead-4',
    name: 'Fernanda Oliveira',
    company: 'Solar Tech Energia Renovável',
    segment: 'Energia Solar',
    city: 'Belo Horizonte - MG',
    phone: '(31) 98432-1100',
    whatsappValid: true,
    email: 'fernanda@solartechmg.com.br',
    website: 'www.solartechmg.com.br',
    siteStatus: 'OK',
    instagram: '@solartech_mg',
    cnpj: '45.678.901/0001-23',
    opportunityScore: 'LOW',
    scoreReason: 'Empresa com site moderno, formulário ativo e canal forte no Instagram.',
    status: 'QUALIFICADO',
    origin: 'Indicação / Scraping',
    estimatedValue: 35000,
    lastInteraction: '2026-08-05 16:00',
    lastChannel: 'EMAIL',
    notes: 'Interessada em automação de atendimento via WhatsApp SDR para equipe de vendas.',
    createdAt: '2026-08-02',
  },
  {
    id: 'lead-5',
    name: 'Marcelo Rossi',
    company: 'Mecânica e Autocenter Rossi',
    segment: 'Automotivo',
    city: 'Curitiba - PR',
    phone: '(41) 99887-6655',
    whatsappValid: true,
    email: 'marcelo@autocenterrossi.com',
    website: '',
    siteStatus: 'SEM_SITE',
    instagram: '@autocenterrossi',
    cnpj: '56.789.012/0001-34',
    opportunityScore: 'HIGH',
    scoreReason: 'Centro automotivo grande sem site para agendamentos e orçamentos rápidos.',
    status: 'PROPOSTA',
    origin: 'Google Maps Scraping',
    estimatedValue: 9800,
    lastInteraction: '2026-08-06 14:10',
    lastChannel: 'WHATSAPP',
    notes: 'Proposta enviada pelo AI SDR com link de pagamento e escopo em PDF.',
    createdAt: '2026-08-01',
  },
  {
    id: 'lead-6',
    name: 'Juliana Paes',
    company: 'Estética & Beleza Spa',
    segment: 'Estética',
    city: 'Florianópolis - SC',
    phone: '(48) 99111-2233',
    whatsappValid: true,
    email: 'juliana@esteticaspa.com.br',
    website: 'www.esteticaspa.com.br',
    siteStatus: 'DESATUALIZADO',
    instagram: '@esteticaspa_florianopolis',
    cnpj: '67.890.123/0001-45',
    opportunityScore: 'MEDIUM',
    scoreReason: 'Site antigo sem botão direto para WhatsApp e sem catálogo de tratamentos.',
    status: 'FECHADO',
    origin: 'Google Maps Scraping',
    estimatedValue: 18000,
    lastInteraction: '2026-08-05 11:20',
    lastChannel: 'WHATSAPP',
    notes: 'Contrato assinado! Agendada reunião de onboarding com equipe técnica.',
    createdAt: '2026-07-28',
  },
  {
    id: 'lead-7',
    name: 'Lucas Martins',
    company: 'Restaurante Sabor & Arte',
    segment: 'Gastronomia',
    city: 'Porto Alegre - RS',
    phone: '(51) 98555-4433',
    whatsappValid: true,
    email: 'lucas@saborearte.com.br',
    website: '',
    siteStatus: 'SEM_SITE',
    instagram: '@saborearte_poa',
    cnpj: '78.901.234/0001-56',
    opportunityScore: 'HIGH',
    scoreReason: 'Restaurante famoso localmente mas sem cardápio digital e sem site institucional.',
    status: 'NOVO_LEAD',
    origin: 'Google Maps Scraping',
    estimatedValue: 6500,
    createdAt: '2026-08-06',
  },
  {
    id: 'lead-8',
    name: 'Amanda Viana',
    company: 'Arquitetura e Interiores Viana',
    segment: 'Arquitetura',
    city: 'Goiânia - GO',
    phone: '(62) 99333-7788',
    whatsappValid: true,
    email: 'amanda@vianaarquitetura.com',
    website: 'www.vianaarquitetura.com',
    siteStatus: 'DESATUALIZADO',
    instagram: '@viana_arquitetura',
    cnpj: '89.012.345/0001-67',
    opportunityScore: 'MEDIUM',
    scoreReason: 'Portfólio desatualizado desde 2022. Baixa conversão de leads no site atual.',
    status: 'CONTATO_INICIADO',
    origin: 'Google Scraping',
    estimatedValue: 14000,
    lastInteraction: '2026-08-06 08:40',
    lastChannel: 'EMAIL',
    createdAt: '2026-08-05',
  }
];

export const initialAgents: Agent[] = [
  {
    id: 'agent-1',
    name: 'Lucas AI - SDR Consultivo',
    role: 'SDR Consultivo Outbound',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250',
    tone: 'consultivo',
    objective: 'marcar_reuniao',
    channel: 'MULTICANAL',
    active: true,
    totalConversations: 842,
    conversionRate: 28.5,
    customPrompt: 'Você é Lucas, um especialista consultivo B2B. Analise a empresa do lead (se tem site ou não) e faça uma abordagem amigável e direta, destacando o problema de não ter site ou ter um site desatualizado. Convide para um café virtual de 15 minutos.',
  },
  {
    id: 'agent-2',
    name: 'Sofia AI - BDR Inbound & Qualificação',
    role: 'BDR Qualificação Rápida',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250',
    tone: 'formal',
    objective: 'qualificar',
    channel: 'WHATSAPP',
    active: true,
    totalConversations: 610,
    conversionRate: 32.1,
    customPrompt: 'Você é Sofia, especialista em qualificação de empresas B2B. Faça 3 perguntas rápidas para entender se a empresa possui orçamento e decisão rápida.',
  },
  {
    id: 'agent-3',
    name: 'Marcio AI - SDR Agressivo de Vendas',
    role: 'SDR Outbound High-Ticket',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250',
    tone: 'agressivo',
    objective: 'vender',
    channel: 'WHATSAPP',
    active: false,
    totalConversations: 390,
    conversionRate: 19.8,
    customPrompt: 'Abordagem direta no dor do cliente. Mostre o quanto ele está perdendo dinheiro por mês sem presença digital e ofereça uma solução imediata.',
  },
];

export const initialCadences: Cadence[] = [
  {
    id: 'cad-1',
    name: 'Cadência Outbound - Alta Oportunidade (Sem Site)',
    targetSegment: 'Empresas sem site no Google Maps',
    stepsCount: 4,
    activeLeads: 124,
    completedLeads: 412,
    active: true,
    steps: [
      {
        id: 'step-1',
        day: 1,
        channel: 'WHATSAPP',
        title: 'Abordagem Inicial WhatsApp (Oportunidade de Site)',
        contentTemplate: 'Olá {nome}, tudo bem? Vi sua empresa ({empresa}) no Google em {cidade}. Notei que vocês não possuem um site oficial cadastrado. Hoje mais de 70% dos clientes buscam no Google antes de fechar. Posso te enviar um projeto rápido sem compromisso?',
        autoSend: true,
      },
      {
        id: 'step-2',
        day: 2,
        channel: 'EMAIL',
        title: 'Apresentação Institucional & Casos de Sucesso',
        contentTemplate: 'Assunto: Como a {empresa} pode captar mais clientes em {cidade}\n\nOlá {nome},\n\nOntem te mandei uma mensagem no WhatsApp sobre a presença online da {empresa}. Criamos recentemente soluções completas de atendimento e site para empresas do segmento de {segmento}.\n\nPodemos conversar amanhã às 10h?',
        autoSend: true,
      },
      {
        id: 'step-3',
        day: 4,
        channel: 'WHATSAPP',
        title: 'Follow-up WhatsApp (Pergunta Direta)',
        contentTemplate: 'Fala {nome}! Conseguiu ver a mensagem anterior? Preparei uma prévia visual de como ficaria a presença digital da {empresa}. Quer dar uma olhada?',
        autoSend: true,
      },
      {
        id: 'step-4',
        day: 7,
        channel: 'EMAIL',
        title: 'Email de Encerramento (Break-up)',
        contentTemplate: 'Assunto: Última tentativa - {empresa}\n\nOlá {nome},\n\nImagino que sua rotina esteja corrida. Como não tive retorno, estou encerrando nossas tentativas por aqui. Caso queira modernizar a {empresa} no futuro, é só me responder por aqui!',
        autoSend: true,
      },
    ],
  },
  {
    id: 'cad-2',
    name: 'Cadência Nurturing - Site Desatualizado',
    targetSegment: 'Empresas com site antigo/lento',
    stepsCount: 3,
    activeLeads: 85,
    completedLeads: 198,
    active: true,
    steps: [
      {
        id: 'step-21',
        day: 1,
        channel: 'WHATSAPP',
        title: 'Feedback Técnico no Site Atual',
        contentTemplate: 'Olá {nome}, vi o site da {empresa} e notei que ele não está otimizado para celulares. Posso te mandar uma análise gratuita dos pontos a melhorar?',
        autoSend: true,
      },
      {
        id: 'step-22',
        day: 3,
        channel: 'EMAIL',
        title: 'Relatório Auditado da {empresa}',
        contentTemplate: 'Olá {nome}, preparei um checklist rápido com 5 falhas no site da {empresa} que fazem você perder clientes em {cidade}.',
        autoSend: true,
      },
      {
        id: 'step-23',
        day: 6,
        channel: 'WHATSAPP',
        title: 'Follow-up de Agendamento',
        contentTemplate: '{nome}, tem 10 minutinhos essa semana para conversarmos sobre como transformar o site da {empresa} em uma máquina de vendas?',
        autoSend: true,
      }
    ],
  },
];

export const initialWhatsappDispatches: WhatsappDispatch[] = [
  {
    id: 'disp-1',
    campaignName: 'Disparo Massivo - Imobiliárias SP',
    totalLeads: 150,
    sentCount: 150,
    deliveredCount: 148,
    readCount: 112,
    repliedCount: 42,
    status: 'CONCLUIDO',
    templateMessage: 'Olá {nome}, vi a {empresa} no Google. Vocês estão aceitando novos clientes em {cidade} neste mês?',
    createdAt: '2026-08-06 09:00',
  },
  {
    id: 'disp-2',
    campaignName: 'Campanha Clínicas Odonto - Campinas',
    totalLeads: 80,
    sentCount: 52,
    deliveredCount: 50,
    readCount: 34,
    repliedCount: 14,
    status: 'EM_ANDAMENTO',
    templateMessage: 'Doutor(a) {nome}, como a {empresa} faz a gestão de agendamentos no WhatsApp hoje?',
    createdAt: '2026-08-06 13:30',
  },
];

export const initialEmailTemplates: EmailTemplate[] = [
  {
    id: 'tpl-1',
    title: 'Abordagem Fria - Foco em Solução de Site',
    subject: '{empresa} + Oportunidade de Novos Clientes em {cidade}',
    body: `Olá {nome},

Acompanho o mercado de {segmento} em {cidade} e percebi que a {empresa} possui um grande potencial de crescimento.

Atualmente ajudamos empresas do seu setor a automatizar o atendimento de novos clientes via WhatsApp e criar uma presença digital moderna e responsiva.

Gostaria de ver uma demonstração de 10 minutos sem compromisso?

Atenciosamente,
Equipe AutoSDR`,
    category: 'prospeccao_fria',
  },
  {
    id: 'tpl-2',
    title: 'Follow-up Estudo de Caso B2B',
    subject: 'Como ajudamos empresas como a {empresa} a dobrar vendas',
    body: `Olá {nome},

Recentemente ajudamos um cliente do segmento de {segmento} a aumentar em 140% os agendamentos semanais via WhatsApp automatizado com IA.

Gostaria de aplicar essa mesma estratégia na {empresa}?

Responda "SIM" a este e-mail que te envio o caso de estudo completo!`,
    category: 'followup',
  },
];

export const initialIntegrations: Integration[] = [
  {
    id: 'int-1',
    name: 'WhatsApp Business API (Evolution/Z-API)',
    description: 'Instância de envio automatizado de WhatsApp com simulação humana de digitação.',
    category: 'whatsapp',
    connected: true,
    iconName: 'MessageSquare',
    lastSync: 'Hoje às 15:30',
    details: 'Sessão "+55 11 99999-8888" - Ativa & Conectada',
  },
  {
    id: 'int-2',
    name: 'Google Maps & Web Scraping Engine',
    description: 'Buscador automatizado de empresas por cidade, segmento e presença digital.',
    category: 'scraping',
    connected: true,
    iconName: 'Search',
    lastSync: 'Sempre Operando',
    details: 'Motor de Busca Google V4 Ativo (Sem Limites)',
  },
  {
    id: 'int-3',
    name: 'API Receita Federal (Consulta CNPJ)',
    description: 'Enriquecimento automático de dados cadastrais, sócios e situação cadastral por CNPJ.',
    category: 'cnpj',
    connected: true,
    iconName: 'Building2',
    lastSync: 'Sempre Operando',
    details: 'Integração RFB Ativa',
  },
  {
    id: 'int-4',
    name: 'Servidor Email SMTP / SendGrid',
    description: 'Disparador de sequências de email outbound com alta entregabilidade.',
    category: 'email',
    connected: true,
    iconName: 'Mail',
    lastSync: 'Hoje às 14:00',
    details: 'SMTP com DKIM/SPF Verificado',
  },
  {
    id: 'int-5',
    name: 'Pipedrive / HubSpot Sync (CRM)',
    description: 'Sincronização automática de oportunidades qualificadas com seu CRM existente.',
    category: 'crm',
    connected: false,
    iconName: 'RefreshCw',
    details: 'Chave de API não configurada',
  },
];
